// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamer.proto

package gamer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47a420919a329fb, []int{0}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ActionInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId               string   `protobuf:"bytes,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	TotalRound           int32    `protobuf:"varint,3,opt,name=totalRound,proto3" json:"totalRound,omitempty"`
	CurrentRound         int32    `protobuf:"varint,4,opt,name=currentRound,proto3" json:"currentRound,omitempty"`
	Data                 []string `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionInput) Reset()         { *m = ActionInput{} }
func (m *ActionInput) String() string { return proto.CompactTextString(m) }
func (*ActionInput) ProtoMessage()    {}
func (*ActionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47a420919a329fb, []int{1}
}

func (m *ActionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionInput.Unmarshal(m, b)
}
func (m *ActionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionInput.Marshal(b, m, deterministic)
}
func (m *ActionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionInput.Merge(m, src)
}
func (m *ActionInput) XXX_Size() int {
	return xxx_messageInfo_ActionInput.Size(m)
}
func (m *ActionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionInput.DiscardUnknown(m)
}

var xxx_messageInfo_ActionInput proto.InternalMessageInfo

func (m *ActionInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ActionInput) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *ActionInput) GetTotalRound() int32 {
	if m != nil {
		return m.TotalRound
	}
	return 0
}

func (m *ActionInput) GetCurrentRound() int32 {
	if m != nil {
		return m.CurrentRound
	}
	return 0
}

func (m *ActionInput) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type ActionOutput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionOutput) Reset()         { *m = ActionOutput{} }
func (m *ActionOutput) String() string { return proto.CompactTextString(m) }
func (*ActionOutput) ProtoMessage()    {}
func (*ActionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47a420919a329fb, []int{2}
}

func (m *ActionOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionOutput.Unmarshal(m, b)
}
func (m *ActionOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionOutput.Marshal(b, m, deterministic)
}
func (m *ActionOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionOutput.Merge(m, src)
}
func (m *ActionOutput) XXX_Size() int {
	return xxx_messageInfo_ActionOutput.Size(m)
}
func (m *ActionOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ActionOutput proto.InternalMessageInfo

func (m *ActionOutput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ActionOutput) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "gamer.PingMessage")
	proto.RegisterType((*ActionInput)(nil), "gamer.ActionInput")
	proto.RegisterType((*ActionOutput)(nil), "gamer.ActionOutput")
}

func init() { proto.RegisterFile("gamer.proto", fileDescriptor_d47a420919a329fb) }

var fileDescriptor_d47a420919a329fb = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x6a, 0x03, 0x21,
	0x14, 0x85, 0x33, 0x66, 0x1c, 0xc8, 0x9d, 0xd0, 0xc5, 0x2d, 0x14, 0x09, 0xb4, 0x0c, 0xae, 0x66,
	0x15, 0x4a, 0xf2, 0x04, 0x5d, 0x95, 0x2c, 0x4a, 0x8b, 0x6f, 0x60, 0xa3, 0x0c, 0x42, 0xab, 0xc1,
	0x5c, 0x1f, 0xa3, 0xef, 0x5c, 0x46, 0xfb, 0x33, 0x09, 0xb3, 0xf3, 0x7e, 0xde, 0xa3, 0xe7, 0x1c,
	0x68, 0x07, 0xfd, 0x69, 0xe3, 0xf6, 0x14, 0x03, 0x05, 0xe4, 0x79, 0x90, 0xf7, 0xd0, 0xbe, 0x39,
	0x3f, 0xbc, 0xd8, 0xf3, 0x59, 0x0f, 0x16, 0x6f, 0x80, 0x39, 0x23, 0xaa, 0xae, 0xea, 0x57, 0x8a,
	0x39, 0x23, 0xbf, 0x2a, 0x68, 0x9f, 0x8e, 0xe4, 0x82, 0x3f, 0xf8, 0x53, 0xa2, 0xeb, 0x7b, 0xbc,
	0x83, 0x66, 0x7c, 0xe7, 0x60, 0x04, 0xcb, 0xec, 0x67, 0xc2, 0x07, 0x00, 0x0a, 0xa4, 0x3f, 0x54,
	0x48, 0xde, 0x88, 0x65, 0x57, 0xf5, 0x5c, 0x4d, 0x08, 0x4a, 0x58, 0x1f, 0x53, 0x8c, 0xd6, 0x53,
	0xd9, 0xa8, 0xf3, 0xc6, 0x05, 0x43, 0x84, 0xda, 0x68, 0xd2, 0x82, 0x77, 0xcb, 0x7e, 0xa5, 0xf2,
	0x59, 0xee, 0x60, 0x5d, 0xec, 0xbc, 0x26, 0x9a, 0xf3, 0xf3, 0xab, 0x61, 0xff, 0x9a, 0x9d, 0x07,
	0xfe, 0x3c, 0x66, 0xc5, 0x47, 0xa8, 0xc7, 0xac, 0x88, 0xdb, 0x52, 0xc4, 0x24, 0xf8, 0x66, 0x86,
	0xc9, 0x05, 0xee, 0xa1, 0x29, 0xdf, 0xfd, 0x69, 0x26, 0x65, 0x6c, 0x6e, 0x2f, 0x58, 0x71, 0x24,
	0x17, 0xef, 0x4d, 0x2e, 0x78, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x19, 0xf9, 0xe7, 0x9e, 0x6f,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GamerClient is the client API for Gamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GamerClient interface {
	Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
	Action(ctx context.Context, in *ActionInput, opts ...grpc.CallOption) (*ActionOutput, error)
}

type gamerClient struct {
	cc *grpc.ClientConn
}

func NewGamerClient(cc *grpc.ClientConn) GamerClient {
	return &gamerClient{cc}
}

func (c *gamerClient) Ping(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := c.cc.Invoke(ctx, "/gamer.Gamer/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gamerClient) Action(ctx context.Context, in *ActionInput, opts ...grpc.CallOption) (*ActionOutput, error) {
	out := new(ActionOutput)
	err := c.cc.Invoke(ctx, "/gamer.Gamer/Action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GamerServer is the server API for Gamer service.
type GamerServer interface {
	Ping(context.Context, *PingMessage) (*PingMessage, error)
	Action(context.Context, *ActionInput) (*ActionOutput, error)
}

func RegisterGamerServer(s *grpc.Server, srv GamerServer) {
	s.RegisterService(&_Gamer_serviceDesc, srv)
}

func _Gamer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gamer.Gamer/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamerServer).Ping(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gamer_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GamerServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gamer.Gamer/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GamerServer).Action(ctx, req.(*ActionInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gamer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gamer.Gamer",
	HandlerType: (*GamerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Gamer_Ping_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _Gamer_Action_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gamer.proto",
}
