# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gamer_pb2 as gamer__pb2


class GamerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/gamer.Gamer/Ping',
        request_serializer=gamer__pb2.PingMessage.SerializeToString,
        response_deserializer=gamer__pb2.PingMessage.FromString,
        )
    self.Action = channel.unary_unary(
        '/gamer.Gamer/Action',
        request_serializer=gamer__pb2.ActionInput.SerializeToString,
        response_deserializer=gamer__pb2.ActionOutput.FromString,
        )


class GamerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Action(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GamerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=gamer__pb2.PingMessage.FromString,
          response_serializer=gamer__pb2.PingMessage.SerializeToString,
      ),
      'Action': grpc.unary_unary_rpc_method_handler(
          servicer.Action,
          request_deserializer=gamer__pb2.ActionInput.FromString,
          response_serializer=gamer__pb2.ActionOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gamer.Gamer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
